PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?cls WHERE {
	?s rdfs:subClassOf ?parent .
	FILTER(STRSTARTS(str(?parent), "http://purl.obolibrary.org/obo/NCBITaxon"))
	BIND(str(?parent) AS ?cls)
}
